# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1
  
jobs:
  deployStack:
    docker:
    - image: amazon/aws-cli
    environment:
      name: creating-udacity-instance
      template_file: template.yml
    steps:
    - checkout 
    - run: 
        name: deploying the stack
        command: aws cloudformation create-stack --stack-name $name --template-file $template_file
    - run: echo "Deployment done"

workflows:
  deployingStack:
    # Run the welcome/run job in its own container
    jobs:
      - deployStack