# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1
  
jobs:
  deployStack:
    docker:
    - image: python:3.7-alpine3.11
    environment:
      name: creating-udacity-instance
      template_file: file://template.yml

    steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
        - "3e:47:2c:54:17:cf:14:a6:71:f2:f0:cd:43:bd:42:a4"  
    - run: ssh-keyscan -H 34.252.230.168 >> ~/.ssh/known_hosts          
    - run:
        name: Install dependencies
        command: apk add --update ansible # install the dependencies needed for your playbook
    - run:
        name: Configure server
        command: ansible-playbook -i hosts main-remote.yml

workflows:
  deployingStack:
    # Run the welcome/run job in its own container
    jobs:
      - deployStack