# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1
  
jobs:
  deployStack:
    docker:
    - image: amazon/aws-cli
    environment:
      name: creating-udacity-instance
      template_file: file://template.yml

    steps:
    - checkout 
    - run: AWS_ACCESS_KEY_ID=`curl -H "token: 4764f73f-07a8-44fd-87ed-4fe7d5793d20" --request GET https://api.memstash.io/values/AWS_ACCESS_KEY_ID`
    - run: AWS_SECRET_ACCESS_KEY=`curl -H "token: 4764f73f-07a8-44fd-87ed-4fe7d5793d20" --request GET https://api.memstash.io/values/AWS_SECRET_ACCESS_KEY`
    - run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - run: aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - run: aws configure set default.region eu-west-1
    - run: 
    - run: 
        name: deploying the stack
        command: aws cloudformation create-stack --stack-name $name --template-body $template_file
    - run: echo "Deployment done"

workflows:
  deployingStack:
    # Run the welcome/run job in its own container
    jobs:
      - deployStack